// work_table.h: the work sizes of the five quality steps, for every picture size that was
// measured.
//
// GENERATED by tools\make_work_table.py from tools\work_table.json. Do not edit it by hand.
// Change the table and run the tool again.
//
// The work size is the size the network runs at. For each picture size in the table, five
// work sizes were measured on an RTX 5090, one for each step from 4 (Quality) down to 0
// (Lowest power). A picture size that is not here gets its sizes from the rule in
// common.cpp, quality_rule(), which gives every entry below that is marked as the rule's.
//
// ms is the network's GPU time at that work size, the median of 300 runs after 120 to warm
// up. kept is the share of the network's change that the Blender test picture keeps against
// the reference size, which is the picture fitted into 2560x1440. It is 0 where it was not
// measured.
#pragma once

namespace work_table {

struct Step {
  unsigned short w, h;  // the work size
  float ms;             // the network's GPU milliseconds there
  float kept;           // the share of the network's change that is kept
};

struct Entry {
  unsigned short width, height;  // the picture
  unsigned char kind;            // 0 native, 1 downscaled, 2 short, see quality_rule()
  bool by_rule;                  // the rule gives these five sizes too
  Step step[5];                  // by step, 0 Lowest power to 4 Quality
};

// The step in use when none is asked for, by kind. It is the highest step at which no loss
// was seen in the pictures.
inline constexpr int kDefaultStep[3] = {4, 3, 3};

inline constexpr Entry kEntries[] = {
    {6144, 2560, 1, true, {{1536, 640, 2.365f, 0.8530f}, {2560, 640, 2.698f, 0.9513f}, {2176, 896, 2.839f, 0.9636f}, {2560, 896, 3.029f, 1.0012f}, {2560, 1024, 3.269f, 0.9918f}}},
    {6144, 2526, 1, true, {{1536, 640, 2.365f, 0.8352f}, {2560, 640, 2.699f, 0.9533f}, {2176, 896, 2.839f, 0.9706f}, {2560, 896, 3.030f, 0.9978f}, {2560, 1024, 3.269f, 0.9992f}}},
    {5120, 2160, 1, true, {{1536, 640, 2.365f, 0.8617f}, {2560, 640, 2.698f, 1.0208f}, {2176, 896, 2.837f, 0.9722f}, {2560, 896, 3.025f, 1.0161f}, {2560, 1024, 3.265f, 0.9824f}}},
    {3840, 2160, 1, true, {{1536, 896, 2.585f, 0.9242f}, {2560, 896, 3.028f, 1.1006f}, {2176, 1152, 3.171f, 1.0488f}, {2560, 1152, 3.418f, 1.1006f}, {2560, 1408, 3.841f, 1.0786f}}},
    {5120, 1440, 2, true, {{1536, 384, 2.211f, 0.8993f}, {1536, 512, 2.326f, 0.9020f}, {2176, 512, 2.415f, 0.9529f}, {2176, 640, 2.582f, 0.9886f}, {2560, 640, 2.696f, 1.0228f}}},
    {3840, 1600, 1, true, {{1536, 640, 2.365f, 0.8265f}, {2560, 640, 2.699f, 0.9848f}, {2176, 896, 2.838f, 0.9506f}, {2560, 896, 3.029f, 0.9973f}, {2560, 1024, 3.271f, 0.9864f}}},
    {3000, 2000, 1, true, {{1408, 896, 2.533f, 0.9090f}, {2048, 896, 2.789f, 1.0042f}, {1792, 1152, 2.897f, 0.9569f}, {2048, 1152, 3.058f, 0.9982f}, {2048, 1408, 3.372f, 1.0010f}}},
    {2880, 1800, 1, true, {{1408, 896, 2.533f, 0.9194f}, {2304, 896, 2.895f, 1.0508f}, {1920, 1152, 2.980f, 1.0210f}, {2304, 1152, 3.273f, 1.0463f}, {2304, 1408, 3.592f, 1.0333f}}},
    {3440, 1440, 1, true, {{1536, 640, 2.365f, 0.8987f}, {2560, 640, 2.699f, 1.0234f}, {2176, 896, 2.838f, 0.9904f}, {2560, 896, 3.025f, 1.0009f}, {2560, 1024, 3.269f, 0.9708f}}},
    {3840, 1200, 2, true, {{1536, 512, 2.326f, 0.8721f}, {1536, 640, 2.364f, 0.8700f}, {2176, 640, 2.582f, 0.9674f}, {2560, 640, 2.692f, 1.0324f}, {2560, 768, 2.868f, 0.9946f}}},
    {3840, 1080, 2, true, {{1536, 384, 2.211f, 0.9170f}, {1536, 512, 2.325f, 0.8665f}, {2176, 512, 2.416f, 0.9064f}, {2176, 640, 2.583f, 0.9739f}, {2560, 640, 2.697f, 1.0241f}}},
    {2560, 1440, 0, true, {{1536, 896, 2.585f, 0.9470f}, {2560, 896, 3.025f, 1.0555f}, {2560, 1024, 3.265f, 1.0454f}, {2560, 1152, 3.417f, 1.0513f}, {2560, 1440, 3.936f, 1.0000f}}},
    {1440, 2560, 1, true, {{512, 896, 2.183f, 1.0338f}, {768, 896, 2.248f, 1.0756f}, {640, 1152, 2.306f, 1.1086f}, {768, 1152, 2.370f, 1.0865f}, {768, 1408, 2.407f, 1.0895f}}},
    {2560, 1080, 0, true, {{1536, 640, 2.365f, 0.9507f}, {2560, 640, 2.695f, 1.0494f}, {2560, 768, 2.865f, 1.0201f}, {2560, 896, 3.024f, 1.0109f}, {2560, 1080, 3.413f, 1.0000f}}},
    {1920, 1200, 0, true, {{1152, 768, 2.366f, 0.9443f}, {1920, 768, 2.614f, 1.0368f}, {1920, 896, 2.742f, 1.0564f}, {1920, 1024, 2.853f, 0.9997f}, {1920, 1200, 3.064f, 1.0000f}}},
    {1920, 1080, 0, true, {{1152, 640, 2.306f, 0.9107f}, {1920, 640, 2.523f, 1.0284f}, {1920, 768, 2.613f, 0.9905f}, {1920, 896, 2.742f, 1.0097f}, {1920, 1080, 2.974f, 1.0000f}}},
    {1600, 900, 0, true, {{1024, 512, 2.182f, 0.9322f}, {1600, 512, 2.324f, 1.0021f}, {1600, 640, 2.425f, 1.0255f}, {1600, 768, 2.512f, 1.0062f}, {1600, 900, 2.675f, 1.0000f}}},
    {1400, 1000, 0, true, {{896, 512, 2.175f, 0.9074f}, {1400, 512, 2.264f, 0.9624f}, {1400, 640, 2.333f, 1.0197f}, {1400, 768, 2.403f, 0.9876f}, {1400, 1000, 2.600f, 1.0000f}}},
    {1440, 900, 0, true, {{896, 512, 2.175f, 0.9273f}, {1440, 512, 2.290f, 0.9866f}, {1440, 640, 2.346f, 1.0763f}, {1440, 768, 2.432f, 0.9974f}, {1440, 900, 2.629f, 1.0000f}}},
    {1366, 768, 0, true, {{768, 384, 2.125f, 0.8630f}, {1366, 384, 2.189f, 0.9887f}, {1366, 512, 2.265f, 0.9960f}, {1366, 640, 2.334f, 1.0322f}, {1366, 768, 2.399f, 1.0000f}}},
};

inline constexpr int kEntryCount = (int)(sizeof(kEntries) / sizeof(kEntries[0]));

}  // namespace work_table
